;; -*- mode: eask; lexical-binding: t -*-

(package "magik-company"
         "1.0.0"
         "Magik backend for company-mode")

(website-url "https://github.com/reinierkof/magik-company")
(keywords "convenience")

(package-file "magik-company.el")
(files "*.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "29.1")
(depends-on "magik-mode")
(depends-on "company")
(depends-on "yasnippet")
